version: 2

before:
  hooks:
    - go mod tidy
    # TODO: you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    # TODO: customize binary name if not the same as repository
    # binary: golang-template
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  # TODO: make sure {{.ProjectName}} is the right github repository
  - images:
      - ghcr.io/fopina/{{.ProjectName}}
    tags:
      - '{{ .Version }}'
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
