name: 👷 publish dev

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  goreleaser:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --snapshot

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/**/*.zip
            dist/**/*.tar.gz

      - name: Sanitize branch name
        id: sanitize_branch
        run: |
          SANITIZED_BRANCH=$(echo -n "${{ github.ref_name }}" | tr '/' '-' | tr -c '[:alnum:]-' '-')
          echo sanitized_branch=$SANITIZED_BRANCH >> $GITHUB_OUTPUT

      - name: Create and push manifest for :snapshot tag
        # TODO: is this the list of images to be added to manifest? tag version and architectures?
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }} \
                                 ghcr.io/${{ github.repository }}:v0.0.0-arm64 \
                                 ghcr.io/${{ github.repository }}:v0.0.0-amd64
          docker manifest push ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }}
