name: 👷 publish dev

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  goreleaser:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --snapshot

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/**/*.zip
            dist/**/*.tar.gz

      - name: Create and push manifest for :snapshot tag
        run: |
          docker manifest create ghcr.io/$GITHUB_REPOSITORY:snapshot ghcr.io/$GITHUB_REPOSITORY:v0.0.0-arm64 ghcr.io/$GITHUB_REPOSITORY:v0.0.0-amd64
          docker manifest push ghcr.io/$GITHUB_REPOSITORY:snapshot
